name: CI Assemble, Test, and Publish

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - master
  workflow_call:

jobs:
  test-and-deploy-to-test-pages:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Check java version
        run: java --version

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Install dependencies and build
        run: ./gradlew clean build

      - name: Run tests
        run: ./gradlew test --stacktrace

      - name: Deploy to GitHub Pages (test)
        if: success()
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          ./gradlew wasmJsBrowserDistribution
          mkdir -p out
          cp -r composeApp/build/dist/wasmJs/productionExecutable/* out/
          cd out
          git init
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git checkout -b test
          git add .
          git commit -m "Deploy to GitHub Pages (test)"
          git push -f origin test

      - name: Create PR to master
        if: success()
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: pre-release # 創建一個新分支來提交 PR
          title: 'Merge develop into master'
          body: 'Auto-generated PR to merge changes from develop to master.'

  deploy-to-release-page-master:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.ref == 'refs/heads/master'

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Check java version
        run: java --version

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Install dependencies and build
        run: ./gradlew clean build

      - name: Deploy to GitHub Pages (gh-pages)
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          ./gradlew wasmJsBrowserDistribution
          mkdir -p out
          cp -r composeApp/build/dist/wasmJs/productionExecutable/* out/
          cd out
          git init
          git remote add origin https://github.com/nakiriyuuzu/nakiriyuuzu.github.io.git
          git checkout -b master
          git add .
          git commit -m "Deploy to GitHub Pages (master)"
          git push -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository_owner }}/nakiriyuuzu.github.io.git master