name: Deploy Release

on:
  pull_request:
    types:
      - closed
  workflow_call:

jobs:
  deploy_to_main:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && github.ref == 'refs/heads/master'
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Clean dependency
        run: ./gradlew clean

      - name: Run tests
        run: ./gradlew test --stacktrace

      - name: Build WasmJs
        run: ./gradlew wasmJsBrowserDistribution

      - name: Build Js
        run: ./gradlew jsBrowserDistribution

      - name: Deploy to GitHub Pages (gh-pages)
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          mkdir -p out/js out/wasmJs
          cp -r kotlin-js-template/* out/
          cp -r composeApp/build/dist/js/productionExecutable/* out/js/
          cp -r composeApp/build/dist/wasmJs/productionExecutable/* out/wasmJs/
          cd out
          git init
          git remote add origin https://github.com/${{ github.repository_owner }}/nakiriyuuzu.github.io.git
          git checkout -b master
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -f https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository_owner }}/nakiriyuuzu.github.io.git master