name: Deploy Test

on:
  push:
    branches:
      - develop

jobs:
  test-and-deploy-to-test-pages:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'

    steps:
      - name: Check out the repository
        uses: ./.github/actions/checkout

      - name: Set up JDK 17
        uses: ./.github/actions/setup-java
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Install dependencies and build
        run: ./gradlew clean build

      - name: Run tests
        run: ./gradlew test --stacktrace

      - name: Deploy to GitHub Pages (test)
        if: success()
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          ./gradlew wasmJsBrowserDistribution
          mkdir -p out
          cp -r composeApp/build/dist/wasmJs/productionExecutable/* out/
          cd out
          git init
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git checkout -b test
          git add .
          git commit -m "Deploy to GitHub Pages (test)"
          git push -f origin test

      - name: Create PR to release
        if: success()
        uses: ./.github/actions/create-pull-request
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: release
          title: 'Merge master into release'
          body: 'Auto-generated PR to merge changes from develop to release.'