name: Deploy Test

on:
  push:
    branches:
      - develop

jobs:
#  test-and-deploy:
#    runs-on: ubuntu-latest
#    if: github.ref == 'refs/heads/develop'
#
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'zulu'
#          java-version: 17
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x ./gradlew
#
#      - name: Clean dependency
#        run: ./gradlew clean --daemon
#
#      - name: Run tests
#        run: ./gradlew test --stacktrace --daemon
#
#      - name: Build WasmJs
#        run: ./gradlew wasmJsBrowserDistribution --daemon
#
#      - name: Build Js
#        run: ./gradlew jsBrowserDistribution --daemon
#
#      - name: Setup Git Config
#        run: |
#          git config --global user.name 'github-actions'
#          git config --global user.email 'github-actions@github.com'
#
#      - name: Deploy to GitHub Pages (test)
#        if: success()
#        run: |
#          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
#          mkdir -p out/js out/wasmJs
#          cp -r kotlin-js-template/* out/
#          cp -r composeApp/build/dist/js/productionExecutable/* out/js/
#          cp -r composeApp/build/dist/wasmJs/productionExecutable/* out/wasmJs/
#          cd out
#          git init
#          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
#          git checkout -b test
#          git add .
#          git commit -m "Deploy to GitHub Pages (test)"
#          git push -f origin test
#
#      - name: Rebase Develop into Release
#        run: |
#          git fetch origin
#          git checkout release || git checkout -b release
#          git merge develop --no-ff --allow-unrelated-histories
#          git push origin release || git push origin develop:release --force

  create_pull-request:
    runs-on: ubuntu-latest
    needs: test-and-deploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: release
          branch: master
          title: 'Release: Develop to Master'
          body: 'Auto-generated pull request to merge release branch into master.'
          draft: false
